version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
  db:
    image: neo4j:4.3.2
    ports:
      - "7474:7474"
      - "7687:7687"
    environment: 
      NEO4J_AUTH: none
